name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linting py${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
        pyproject-file: ./pyproject.toml

    - name: Install
      run: |
        uv python install ${{ matrix.python-version }}
        uv sync --group dev --extra viz

    - name: Lint Python Code
      run: |
        uv run ruff check

    - name: Format Check Python Code
      run: |
        uv run ruff format --check

  test:
    runs-on: ${{ matrix.os }}
    name: Unit Testing py${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}
        pyproject-file: ./pyproject.toml

    - name: Install
      run: |
        uv python install ${{ matrix.python-version }}
        uv sync --group dev --extra viz

    - name: test
      run: |
        uv run pytest
