name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        code-dir: ["waveforms", "examples"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install -e .[dev]
    - name: Analysing code in ${{ matrix.code-dir }} directory with Ruff
      run: |
        ruff check ./${{ matrix.code-dir }}
    - name: Check code formatting in ${{ matrix.code-dir }} directory with Black
      run: |
        black --check ./${{ matrix.code-dir }}
